keys:
  - &maddie age1w2e77686e6j87pvapn4uey50mlq9qwdx5knuspq2776hrkesj58qgl3qt4
  - &caspian age165gk3m94v9fptkx2afd4cn5fc4y0ne53zk2fecscpkwl9lgxf4esktx3ue
creation_rules:
  - path_regex: secrets/maddie\.yaml$
    key_groups:
    - age:
      - *maddie
      - *caspian

